{{ config(materialized='ephemeral') }}
SELECT
    AIRPORT_CODE,
    AIRCRAFT_TYPE,
    EFFECTIVE_DATE,
    LANDING_FEE,
    _FIVETRAN_SYNCED,
    _FIVETRAN_DELETED
FROM {{ source('bronze_ref', 'AIRPORT_FEES') }}
WHERE _FIVETRAN_DELETED = FALSE OR _FIVETRAN_DELETED IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY AIRPORT_CODE, AIRCRAFT_TYPE, EFFECTIVE_DATE ORDER BY _FIVETRAN_SYNCED DESC) = 1