{{ config(materialized='ephemeral') }}
SELECT
    AIRCRAFT_TYPE,
    EFFECTIVE_DATE,
    CREW_COST_PER_HOUR,
    MAINT_RESERVE_PER_HOUR,
    _FIVETRAN_SYNCED,
    _FIVETRAN_DELETED
FROM {{ source('bronze_ref', 'AIRCRAFT_COST_RATE') }}
WHERE _FIVETRAN_DELETED = FALSE OR _FIVETRAN_DELETED IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY AIRCRAFT_TYPE, EFFECTIVE_DATE ORDER BY _FIVETRAN_SYNCED DESC) = 1