{{ config(materialized='ephemeral') }}
SELECT
    AIRCRAFT_REG,
    AIRCRAFT_TYPE,
    FUEL_BURN_RATE,
    MAINT_RESERVE_RATE,
    _FIVETRAN_SYNCED,
    _FIVETRAN_DELETED
FROM {{ source('bronze_amos', 'AIRCRAFT_FLEET') }}
WHERE _FIVETRAN_DELETED = FALSE OR _FIVETRAN_DELETED IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY AIRCRAFT_REG ORDER BY _FIVETRAN_SYNCED DESC) = 1