-- ============================================================
-- 1. DATABASES
-- ============================================================
CREATE DATABASE IF NOT EXISTS NFP_BRONZE;
CREATE DATABASE IF NOT EXISTS NFP_SILVER;
CREATE DATABASE IF NOT EXISTS NFP_GOLD;

-- ============================================================
-- 2. SCHEMAS
-- BRONZE_{SOURCE} schemas are created automatically by Fivetran
-- Pre-create admin schemas only
-- ============================================================
CREATE SCHEMA IF NOT EXISTS NFP_BRONZE.TAGS;
CREATE SCHEMA IF NOT EXISTS NFP_GOLD.POLICIES;

-- Pre-create Silver schemas (one per source system)
CREATE SCHEMA IF NOT EXISTS NFP_SILVER.SILVER_AIMS;
CREATE SCHEMA IF NOT EXISTS NFP_SILVER.SILVER_AMADEUS;
CREATE SCHEMA IF NOT EXISTS NFP_SILVER.SILVER_CHAMP;
CREATE SCHEMA IF NOT EXISTS NFP_SILVER.SILVER_EPICOR;
CREATE SCHEMA IF NOT EXISTS NFP_SILVER.SILVER_AMOS;
CREATE SCHEMA IF NOT EXISTS NFP_SILVER.SILVER_REF;

-- ============================================================
-- 3. WAREHOUSES
-- ============================================================
CREATE WAREHOUSE IF NOT EXISTS NFP_LOADING_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Fivetran ingestion warehouse';

CREATE WAREHOUSE IF NOT EXISTS NFP_TRANSFORM_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'dbt Core transformation warehouse';

-- ============================================================
-- 4. ROLES
-- ============================================================
CREATE ROLE IF NOT EXISTS NFP_LOADER_ROLE;
CREATE ROLE IF NOT EXISTS NFP_TRANSFORMER_ROLE;
CREATE ROLE IF NOT EXISTS NFP_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS NFP_COMPLIANCE_ROLE;

GRANT ROLE NFP_LOADER_ROLE      TO ROLE SYSADMIN;
GRANT ROLE NFP_TRANSFORMER_ROLE TO ROLE SYSADMIN;
GRANT ROLE NFP_ANALYST_ROLE     TO ROLE SYSADMIN;
GRANT ROLE NFP_COMPLIANCE_ROLE  TO ROLE SYSADMIN;

-- ============================================================
-- 5. FIVETRAN SERVICE USER
-- ============================================================
CREATE USER IF NOT EXISTS FIVETRAN_USER_NFP
    TYPE = SERVICE
    DEFAULT_ROLE = 'NFP_LOADER_ROLE'
    DEFAULT_WAREHOUSE = 'NFP_LOADING_WH'
    PASSWORD = '{{PLACEHOLDER_SNOWFLAKE_SVC_PASSWORD}}';

GRANT ROLE NFP_LOADER_ROLE TO USER FIVETRAN_USER_NFP;

-- ============================================================
-- 6. FIVETRAN GRANTS (exactly four — RULE F2)
-- Fivetran holds OWNERSHIP of schemas/tables it creates
-- ============================================================
GRANT USAGE ON WAREHOUSE NFP_LOADING_WH       TO ROLE NFP_LOADER_ROLE;
GRANT USAGE ON DATABASE NFP_BRONZE            TO ROLE NFP_LOADER_ROLE;
GRANT CREATE SCHEMA ON DATABASE NFP_BRONZE    TO ROLE NFP_LOADER_ROLE;
GRANT MONITOR ON DATABASE NFP_BRONZE          TO ROLE NFP_LOADER_ROLE;

-- ============================================================
-- 7. TRANSFORMER GRANTS
-- ============================================================
GRANT USAGE ON WAREHOUSE NFP_TRANSFORM_WH     TO ROLE NFP_TRANSFORMER_ROLE;

-- Bronze: read current objects
GRANT USAGE ON DATABASE NFP_BRONZE                       TO ROLE NFP_TRANSFORMER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NFP_BRONZE        TO ROLE NFP_TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES  IN DATABASE NFP_BRONZE       TO ROLE NFP_TRANSFORMER_ROLE;

-- Bronze: FUTURE GRANTS — Fivetran adds new schemas/tables over time (RULE F3)
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE NFP_BRONZE     TO ROLE NFP_TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE TABLES  IN DATABASE NFP_BRONZE    TO ROLE NFP_TRANSFORMER_ROLE;

-- Silver: write access for dbt
GRANT USAGE ON DATABASE NFP_SILVER                       TO ROLE NFP_TRANSFORMER_ROLE;
GRANT CREATE SCHEMA ON DATABASE NFP_SILVER               TO ROLE NFP_TRANSFORMER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NFP_SILVER        TO ROLE NFP_TRANSFORMER_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE NFP_SILVER     TO ROLE NFP_TRANSFORMER_ROLE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE NFP_SILVER TO ROLE NFP_TRANSFORMER_ROLE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE NFP_SILVER TO ROLE NFP_TRANSFORMER_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN DATABASE NFP_SILVER                 TO ROLE NFP_TRANSFORMER_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN DATABASE NFP_SILVER              TO ROLE NFP_TRANSFORMER_ROLE;

-- Gold: write access for dbt
GRANT USAGE ON DATABASE NFP_GOLD                         TO ROLE NFP_TRANSFORMER_ROLE;
GRANT CREATE SCHEMA ON DATABASE NFP_GOLD                 TO ROLE NFP_TRANSFORMER_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE NFP_GOLD       TO ROLE NFP_TRANSFORMER_ROLE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE NFP_GOLD TO ROLE NFP_TRANSFORMER_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN DATABASE NFP_GOLD                TO ROLE NFP_TRANSFORMER_ROLE;

-- ============================================================
-- 8. ANALYST GRANTS (Gold read-only)
-- ============================================================
GRANT USAGE ON DATABASE NFP_GOLD                         TO ROLE NFP_ANALYST_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE NFP_GOLD       TO ROLE NFP_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES  IN DATABASE NFP_GOLD      TO ROLE NFP_ANALYST_ROLE;

-- ============================================================
-- 9. RESOURCE MONITOR
-- Assign to BOTH warehouses — NOTIFY not SUSPEND at 100% (RULE F4)
-- DO SUSPEND aborts in-flight Fivetran syncs — never use it here
-- ============================================================
CREATE RESOURCE MONITOR IF NOT EXISTS NFP_MONITOR WITH
    CREDIT_QUOTA = 100
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS = ('NFP_ADMIN')
    TRIGGERS
        ON 75  PERCENT DO NOTIFY
        ON 90  PERCENT DO NOTIFY
        ON 100 PERCENT DO NOTIFY;

ALTER WAREHOUSE NFP_LOADING_WH   SET RESOURCE_MONITOR = NFP_MONITOR;
ALTER WAREHOUSE NFP_TRANSFORM_WH SET RESOURCE_MONITOR = NFP_MONITOR;